### ISSUE TITLE
css

### ISSUE THREAD

**Issue by Anichki** [Kekson/labrepo#1]
1. სწორად მიუთითე css-ფაილის მისამართი
2. შექმენი ფოლდერი css და იქ ჩადევი შენი style.css, რადგან ვებგვერდზე მუშაობისას დროთა განმავლობაში ძალიან ბევრი ფაილები დაგიგროვდება და ერთად თუ იქნება ძალიან რთული იქნება სასურველი დოკუმენტის პოვნა.
3. შეეცადე chrome developer tool გამოიყენო და კონსოლში ნახავ რა error-ები გაქვს.

**Comment by Kekson** [comment]
ყველაფერი გასაგებია და აუცილებლად გავითვალისწინებ
